version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: plushdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a
      POSTGRES_DB: plush
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
